{
  "hash": "84eeaee173830e22e32fa2c1876f7866",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Obtaining, manipulating, and fitting climate data\"\nsubtitle: \"SPARKLE Session 2 on climate data in infectious disease modelling\"\nformat:\n  training-html: default\npresenter: \"Michael & Roslyn\"\ncontributors:\n  - \"Dr Vassili Kitsios\"\n  - \"Prof. Roslyn Hickson\"\n  - \"Dr Michael Lydeamore\"\n  - \"Claude (Anthropic) did the translation of the existing Python workflow to R Quarto; all content to be checked by the course team\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n<style type=\"text/css\">\n.speaker-note {\n    background-color: #fff8e1;\n    border-left: 4px solid #f9a825;\n    padding: 10px 14px;\n    margin: 14px 0;\n    border-radius: 3px;\n    font-size: 0.92em;\n    color: #5d4037;\n}\n.speaker-note::before {\n    content: \"🗒 Facilitator note: \";\n    font-weight: bold;\n}\n.todo-note {\n    background-color: #fdecea;\n    border-left: 4px solid #d32f2f;\n    padding: 10px 14px;\n    margin: 14px 0;\n    border-radius: 3px;\n    font-size: 0.92em;\n    color: #611a15;\n}\n.todo-note::before {\n    content: \"🚧 TODO (course team): \";\n    font-weight: bold;\n}\n/* Wide printed output (e.g. glimpse, data-frame previews) scrolls sideways\n   instead of wrapping, similar to a pandas data-frame preview. */\n.cell-output-stdout pre {\n    white-space: pre;      /* do not wrap long lines */\n    overflow-x: auto;      /* scroll right instead */\n}\n/* Wide rendered tables (e.g. kable data-frame previews) scroll sideways too. */\n.cell-output-display {\n    overflow-x: auto;\n}\n</style>\n:::\n\n\n::: speaker-note\n**Environment.** The R practicals assume the following packages are installed:\n`jsonlite`, `dplyr`, `tidyr`, `lubridate`, `ggplot2`, `patchwork`, `sf`,\n`terra`, and `ncdf4`. Please confirm these are installed before the session. The\ngeospatial steps (reanalysis and CMIP6) read netCDF and shapefiles directly and\ncan take a little while on first render. Using `freeze: auto` caches them\nafter the first successful render.\n\n**Worked example.** Throughout, the running example is malaria incidence in\nThailand, linked to ERA5 reanalysis climate and CMIP6 future projections.\n:::\n\n# Summary {.tabset .tabset-pills .tabset-fade}\n\nThis session works through the practical workflow of using climate data in\ninfectious disease modelling, with malaria in Thailand as the case study: from\nobtaining raw data through to a fitted statistical model that links climate to\nmalaria incidence, with future projections.\n\nThe session opens by framing the **research question** and then works through \nsix practical parts, with an extension section on fitting an SEIRS transmission \nmodel:\n\n**The research question.** What we are trying to answer, and how it informs what\ndata and modelling we need.\n\n**Part 1: Obtaining the data.** Where the data come from (malaria surveillance, \nclimate reanalysis, future projections, administrative boundaries) and how to \nobtain them.\n\n**Part 2: Malaria case data.** Reading the surveillance line list and \nsummarising cases by month, province, and district.\n\n**Part 3: Environmental variables (reanalysis).** Linking gridded ERA5 climate\ndata to administrative units using a shapefile, and building per-province \nmonthly temperature and rainfall series.\n\n**Part 4: Future climate projections.** Summarising CMIP6 projections under two\nemissions scenarios (SSP1-2.6 and SSP5-8.5) for the same provinces.\n\n**Part 5: Fitting climate to incidence.** A statistical (ARIMA/ARX panel) model\nrelating standardised climate to changes in malaria cases across provinces.\n\n**Part 6: Projecting future cases.** Pushing the fitted statistical model \nforward under the CMIP6 scenarios to project future cases, with the important \ncaveats of long-range extrapolation.\n\n**Optional extension: An SEIRS model.** A (basic) transmission model approach.\n\n::: {.callout-tip}\nWe recommend saving your written answers at the end of each part by printing the\npage (there is a **Print this page** button at the end of each part).\n:::\n\nThis is a port of the python analysis \n(`python_workflow/malaria_workflow.ipynb`), which we have left available for \nthose interested.\n\n---\n\n# The research question\n\n::: speaker-note\nSpend the first few minutes establishing *what we are trying to answer* and \n*what decision it would inform*. Draw out that the question is what tells us \n(a) whether climate data is even relevant, (b) which data we need, and (c) \nwhether it makes sense to project forward. Participants do this same first step \nfor their own work in Session 3.\n:::\n\nIt is important in modelling for the question to determine the methodology, and \nit also informs what data we need. The data available may in turn force us to \nupdate and refine our question and methodology.\n\nFor this case study, our research question is:\n\n> **How do temperature and rainfall relate to malaria incidence across Thailand, \n> and how might that incidence change under future emissions scenarios?**\n\nReading that question tells us:\n\n- a measure of the **outcome**: malaria cases, over time and by location.\n- the **drivers** we hypothesise to matter: temperature and rainfall.\n- a **spatial region**: Thailand. The spatial resolution is often driven by \n  data availability. In this case, we will use provinces (the unit cases are \n  reported in).\n- a **historical period** where we observe outcome and drivers together, to \\\n  *learn* the relationship. This is also often driven by data availability.\n- **future climate** for the same region, to *project* that relationship \n  forward.\n\nThis list is the data we found available, not the initial list assembled. \n\n**What data do you think is missing from this list, and why?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n<p><input type=\"button\" value=\"Print this page\" onClick=\"window.print()\"></p>\n\n::: {.callout-tip collapse=\"true\"}\n## Suggested answer: click to reveal (try to answer yourself first)\n\nThere is no single right answer.\n\nWe were initially planning on relating mosquito vector abundance to the climatic\nvariables, and projecting those forward and linking to malaria incidence via a \ntransmission model tracking humans and vectors. But we couldn't find abundance \ndata in Thailand at the same time period as the malaria incidence data.\n:::\n\n---\n\n# **Part 1:** Obtaining the data\n\n::: speaker-note\nThis part is about *where the data come from* and *why each source was chosen*. \n:::\n\nThe workflow draws on four data sources. Three are used directly in the \nanalysis; the fourth (mosquito occurrence) motivates the approach but is not \ncurrently used. The table below is the quick reference; each source, and why it \nwas chosen, is expanded underneath.\n\n| # | Data | What it is / role | Why this source | Source |\n|---|--------|-------------------|-----------------|-------------|\n| 1 | Malaria cases | national surveillance line list (the outcome) | authoritative, national, open, right resolution | [Thai DDC](https://malaria-api.ddc-malaria.org/study/2year/calendar){target=\"_blank\"} |\n| 2 | Spatial region boundaries | province (ADM1) polygons; aggregate grid to province | official ADM1; names align with the case data | [Open Dev Mekong](https://data.opendevelopmentmekong.net/dataset/thailand-provincial-boundaries){target=\"_blank\"} |\n| 3 | ERA5 reanalysis | gap-free past climate, used to *learn* | state of the art, ~0.25°, complete coverage, open | [Copernicus CDS](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels?tab=download){target=\"_blank\"} |\n| 4 | CMIP6 projections | multi-model future climate, used to *project* | latest coordinated ensemble; scenarios bracket futures | [Copernicus CDS](https://cds.climate.copernicus.eu/datasets/projections-cmip6?tab=download){target=\"_blank\"} |\n\n::: {.callout-tip}\nReanalysis (ERA5) is used to *learn* the relationship between climate and malaria\nover the historical period; the CMIP6 projections are used to *project* that\nrelationship forward under future emissions scenarios.\n:::\n\n**1. Malaria case data (surveillance line list).** Individual records of malaria\nblood draws in Thailand, with date, province, district, and result (*P. vivax* `V`,\n*P. falciparum* `F`, or other). This is the outcome we are modelling, and it comes\nfrom the national surveillance system (Thailand's DDC), so it is authoritative and\nconsistent across the whole country. It is openly queryable via the API (no\ndata-sharing agreement for this aggregated endpoint) and carries date, province,\ndistrict and species per record, at the spatial and temporal resolution we need for\nmonthly climate. Alternatives like WHO country-year totals are too coarse, and\nhospital records are not openly accessible.\n\n*Source and files:* [https://malaria-api.ddc-malaria.org/study/2year/calendar](https://malaria-api.ddc-malaria.org/study/2year/calendar){target=\"_blank\"} , saved as `data/malaria/calendar.json`.\n\n::: {.callout-note appearance=\"minimal\"}\n**DDC** is Thailand's Department of Disease Control (its vector-borne disease division runs the malaria surveillance).\n:::\n\n**2. Administrative boundaries (shape files).** Province boundaries for Thailand. We\nneed province polygons because cases are reported per province but climate is\ngridded; the polygons let us aggregate the grid to the reporting unit. This set was\nchosen because it is the official Thai ADM1 (province) boundaries, so its units and\nnames align with how the surveillance data is reported (name alignment matters: it\nis why some provinces drop out when names do not match), and it is freely available\nin a standard GIS format.\n\n*Source and files:* [https://data.opendevelopmentmekong.net/dataset/thailand-provincial-boundaries](https://data.opendevelopmentmekong.net/dataset/thailand-provincial-boundaries){target=\"_blank\"} , saved under `data/shape_files/tha_admbnda_adm1_rtsd_20190221/`.\n\n::: {.callout-note appearance=\"minimal\"}\nA **shape file** stores polygon boundaries (countries, provinces, districts); **ADM1** is the first sub-national administrative level, here the provinces.\n:::\n\n**3. Climate reanalysis (ERA5).** Gridded, monthly-averaged 2 m temperature (`2t`)\nand total precipitation (`tp`): a physically consistent, gap-free reconstruction of\npast weather, used here to *learn* how climate relates to malaria. We use reanalysis\nrather than weather stations because stations are sparse and gappy, whereas\nreanalysis gives complete fields everywhere, which is essential for giving every\nprovince a climate value. We use ERA5 specifically because it is the current\nstate-of-the-art global reanalysis (~0.25° resolution, well validated, openly\navailable), carrying the variables we want (temperature and precipitation drive\nmosquito abundance and survival) at monthly resolution. It is the de facto standard\nfor climate and health work.\n\n*Source and files:* [https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels?tab=download](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels?tab=download){target=\"_blank\"} , saved under `data/reanalysis/monthly-averaged/`. The required subset is already curated for you; other variables can be downloaded freely from the Copernicus Climate Change Service (C3S) Climate Data Store.\n\n::: {.callout-note appearance=\"minimal\"}\n**ERA5** = ECMWF Re-Analysis, 5th generation (ECMWF is the European Centre for Medium-Range Weather Forecasts; the lineage runs ERA-15, ERA-40, ERA-Interim, ERA5).\n:::\n\n**4. Future climate projections (CMIP6).** A multi-model ensemble of monthly\ntemperature (`tas`) and precipitation (`pr`) for Thailand under two emissions\nscenarios (SSP1-2.6 and SSP5-8.5), used to *project* the learned relationship into\nthe future. We use CMIP6 specifically because it is the latest coordinated\nmulti-model generation (the models underpinning IPCC AR6), delivered in a standard,\ncomparable format, so we can use a multi-model ensemble to represent model\nuncertainty and the SSP scenarios to bracket futures. SSP1-2.6 and SSP5-8.5 were\nchosen as a low- and high-emissions pair to show sensitivity to the pathway. It is\nalso regriddable onto the ERA5 grid, so the historical and future steps stay\nconsistent.\n\n*Source and files:* [https://cds.climate.copernicus.eu/datasets/projections-cmip6?tab=download](https://cds.climate.copernicus.eu/datasets/projections-cmip6?tab=download){target=\"_blank\"} , saved under `data/cmip6/monthly-averaged/`. The data is curated and trimmed to the region for this case study; other variables, scenarios, or the full globe are available from the same Climate Data Store.\n\n::: {.callout-note appearance=\"minimal\"}\n**CMIP6** = Coupled Model Intercomparison Project, 6th phase (\"coupled\" refers to coupled atmosphere and ocean models). In an **SSP** (Shared Socioeconomic Pathway) label such as SSP1-2.6, the first digit is the socioeconomic story (1 = sustainability, 5 = fossil-fuel-intensive) and the second is the resulting radiative forcing (2.6 vs 8.5 W/m² by 2100, i.e. low vs high warming).\n:::\n\n**Mosquito occurrence (GBIF), considered but not used.** Mosquito occurrence records\nfor Thailand. We explored GBIF because it is the largest aggregator of open occurrence\nrecords, so it is the obvious first place to look for vector data. It is not used here\nbecause it gives *occurrence*, not *abundance*, and has no samples after 2022, so it\ndoes not overlap the 2025 to 2026 malaria data. For now we relate malaria incidence in\nhumans to environmental variables directly (the approach taken in Part 5); regardless,\nthis is a good, straightforward way to test whether environmental variables such as\nthese are affecting the health outcomes of interest, and which ones. A natural\nextension is to obtain overlapping mosquito data, learn the influence of temperature on\nthe mosquito population, then the impact of that population on malaria infections via a\ntransmission model.\n\n*Source and files:* [https://www.gbif.org/dataset/db4211d6-b480-4bc5-9202-87f2072c4b12](https://www.gbif.org/dataset/db4211d6-b480-4bc5-9202-87f2072c4b12){target=\"_blank\"} (not downloaded; not part of the analysis).\n\n::: {.callout-note appearance=\"minimal\"}\n**GBIF** is the Global Biodiversity Information Facility, the largest aggregator \nof open species-occurrence records.\n:::\n\n::: {.callout-note}\n## Obtaining the data yourself\nThe Copernicus Climate Data Store (ERA5 and CMIP6) requires a free account and,\nfor bulk downloads, the CDS API (a `~/.cdsapirc` key file). Because these\ndownloads need accounts/API keys and can be large, they are not run as code \nhere. Instead, the curated subset needed for this tutorial is provided \nseparately in the `data/` folder at the repository root.\n:::\n\n## Ideal vs achievable workflows\n\n::: speaker-note\nThe key discussion point here: what you *want* to do is often constrained by the\ndata you can actually get. \n:::\n\nThe right workflow is rarely the most sophisticated one, but one that fits \nboth your question and that your data can actually support. For malaria, the \nbiologically known climate-sensitive link is the *mosquito* population: \ntemperature and breeding site available, typically via rainfall, drive mosquito \nabundance, which in turn drives transmission. \n\n| Approach | Pipeline | Data needed | Biological fidelity |\n|---|---|---|---|\n| **Ideal** (vector-explicit) | climate → mosquito abundance → transmission model → incidence | overlapping spatio-temporal local mosquito **abundance** data *and* climate | highest |\n| **Simplest** (direct statistical) | climate → incidence | overlapping spatio-temporal case data + climate | lowest: no explicit mechanism |\n| **Achievable here** (climate-forced SEIRS) | climate → transmission model (transmission forced by climate) → incidence | overlapping spatio-temporal case data + climate | medium: climate link through implicit vector dynamics |\n\nFor this example we wanted the **ideal** path, but we couldn't find mosquito \nabundance data that spatio-temporally overlapped the malaria period (see the \nGBIF note above), so we use the lower two tiers: a direct statistical model \n(Part 5) and a climate-forced SEIRS model (the optional section at the end of \nthis session). Both skip the mosquito layer. This is a data-driven compromise.\n\n**1.1 For each of the four data sources above, what alternative dataset or \napproach could you use in its place? Think about substitutes for ERA5, for \nCMIP6, and for the provincial case and boundary data, and what you would trade \noff by switching. If you identfied other data earlier, what sources are there?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**1.2 Reanalysis is used to *learn* the climate–disease relationship and CMIP6\nprojections are used to *project* it into the future. Why can we not simply use \nthe future projections to learn the relationship in the first place?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n<p><input type=\"button\" value=\"Print this page\" onClick=\"window.print()\"></p>\n\n::: {.callout-tip collapse=\"true\"}\n## Solutions for Part 1: click to reveal (try the questions first)\n\n**1.1** There are alternatives for every source, each with trade-offs. For the\nreanalysis, other products such as MERRA-2 or JRA-55, or gridded observational\ndatasets (for example CHIRPS for rainfall, CRU for temperature), could replace \nERA5, trading spatial and temporal resolution and which variables are available. \nFor the projections, CMIP5 or a downscaled or emulated ensemble could replace \nCMIP6, changing resolution, the scenario definitions, and the model spread. For \nthe boundaries, a different administrative product or a gridded population layer \ncould be used, changing which spatial unit cases are aggregated to. For the case \ndata, a different health outcome or a modelled incidence surface could stand in \nwhere line-list surveillance is not available. The point is to notice that each \nswap changes resolution, coverage, or assumptions rather than to find one right \nanswer.\n\n**1.2** Future projections are, by construction, *projections*: they describe\nplausible futures, not observed weather, and there is no malaria data from the\nfuture to pair them with. We can only learn a relationship where we observe \n*both* climate and cases together, which means the historical/reanalysis period. \nThe projections are then used to *project* that learned relationship forward.\n:::\n\n---\n\n# **Part 2:** Malaria case data\n\n::: speaker-note\nThis part reads the surveillance line list and aggregates it. The key teaching\npoints are: \n\n(1) surveillance data are messy and unevenly reported across provinces and time; \nthis is why we later restrict to provinces with enough data; and \n\n(2) aggregating to monthly counts per province gives us the response variable\nthat we will link to climate. \n\nThe code is a direct translation of the Python `pandas` workflow. Have \nparticipants run it and *consider* the province panels (question 2.2) before \nmoving on.\n:::\n\nWe start from the surveillance line list: one row per blood draw, with a date,\nprovince, district, and result. We read it, parse the dates, and aggregate to\nmonthly counts.\n\n**Run the code below, then work through the questions underneath it.**\n\nFirst read in the data from the json file.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(jsonlite)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(lubridate)\nlibrary(ggplot2)\nlibrary(patchwork)\nlibrary(here)\n\n# Locate the data\ndata_dir <- here::here(\"data\")\n\n# Read the JSON line list and parse dates ---------------------------------\ndf <- fromJSON(file.path(data_dir, \"malaria\", \"calendar.json\"))\ndf <- df %>%\n  mutate(\n    date_daily = as.Date(as.character(blood_draw_date), format = \"%Y%m%d\"),\n    month      = floor_date(date_daily, \"month\")\n  )\n\n# Preview what we have loaded ---------------------------------------------\nknitr::kable(head(df, 5))      # the first 5 rows as a clean table in quarto\n\ncat(\"Number of unique province names:\", n_distinct(df$province_en), \"\\n\")\ncat(\"Number of unique district names:\", n_distinct(df$district_en), \"\\n\")\ncat(\"Number of unique blood_draw_date:\", n_distinct(df$blood_draw_date), \"\\n\")\n```\n\n::: {.cell-output-display}\n\n\n|data_guid                                      |blood_draw_date |sex |province_id |province_th |province_en         |district_id |district_th |district_en    |result |nation  |area |age |occupation_th |occupation_en     |org_type |weight |temperature |date_daily |month      |\n|:----------------------------------------------|:---------------|:---|:-----------|:-----------|:-------------------|:-----------|:-----------|:--------------|:------|:-------|:----|:---|:-------------|:-----------------|:--------|:------|:-----------|:----------|:----------|\n|712025010128b09a82-ea03-4954-9d16-ca54c3a9aefc |20250101        |M   |71          |กาญจนบุรี     |Kanchanaburi        |7104        |ศรีสวัสดิ์      |SI SAWAT       |V      |Thai    |B1   |17  |รับจ้าง         |Laborer           |odpc     |66.0   |            |2025-01-01 |2025-01-01 |\n|77202501015c89d666-e30d-4e0f-bb0e-4c8fb8872d71 |20250101        |M   |77          |ประจวบคีรีขันธ์ |Prachuap Khiri Khan |7704        |บางสะพาน    |BANG SAPHAN    |V      |Thai    |A1   |34  |รับจ้าง         |Laborer           |odpc     |62.0   |            |2025-01-01 |2025-01-01 |\n|70202501017e8c57c5-94cd-4517-a251-2ec82bc1532b |20250101        |F   |70          |ราชบุรี       |Ratchaburi          |7003        |สวนผึ้ง       |SUAN PHUENG    |V      |Migrant |A1   |12  |เด็ก/นักเรียน    |children/students |odpc     |22.2   |36.20       |2025-01-01 |2025-01-01 |\n|58202501019fe2ee4c-2774-45b2-9eb1-cf8a1e783935 |20250101        |M   |58          |แม่ฮ่องสอน    |Mae Hong Son        |5804        |แม่สะเรียง    |MAE SARIANG    |F      |Thai    |A2   |37  |รับจ้าง         |Laborer           |odpc     |60.0   |39.90       |2025-01-01 |2025-01-01 |\n|712025010193ae8743-8ecc-4849-85a4-6261eeca5656 |20250101        |M   |71          |กาญจนบุรี     |Kanchanaburi        |7107        |ทองผาภูมิ     |THONG PHA PHUM |Other  |Migrant |A2   |20  |รับจ้าง         |Laborer           |odpc     |73.0   |            |2025-01-01 |2025-01-01 |\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of unique province names: 66 \nNumber of unique district names: 340 \nNumber of unique blood_draw_date: 517 \n```\n\n\n:::\n:::\n\n\nCounts for Thailand per month and per day\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Total counts per day and per month --------------------------------------\ncounts_per_day <- df %>% count(date_daily, name = \"count\") %>% arrange(date_daily)\ncounts_per_month <- df %>% count(month, name = \"count\") %>% arrange(month)\n\np_day <- ggplot(counts_per_day, aes(date_daily, count)) +\n  geom_line() +\n  scale_x_date(date_breaks = \"1 month\", date_labels = \"%b %Y\") +\n  labs(x = \"date\", y = \"total daily counts\") +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n\np_month <- ggplot(counts_per_month, aes(month, count)) +\n  geom_line() + geom_point(size = 1) +\n  scale_x_date(date_breaks = \"1 month\", date_labels = \"%b %Y\") +\n  labs(x = \"date (monthly total, aligned to first of month)\",\n       y = \"total monthly counts\") +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n\nprint(p_day / p_month)\n```\n\n::: {.cell-output-display}\n![](session2_climate_data_files/figure-html/part2-counts-1.png){fig-align='center' width=960}\n:::\n:::\n\n\nCounts per province per month: since we will be building models estimating the infection counts per province per month, including the impact of the climate.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Counts per province per month -------------------------------------------\ncounts_prov_month <- df %>%\n  count(month, province_en, name = \"Count\") %>%\n  arrange(month, province_en)\n\n# Keep provinces with more than 12 months of reported cases \nprov_order <- unique(counts_prov_month$province_en)\nselected_provinces <- prov_order[\n  vapply(prov_order,\n         function(p) sum(counts_prov_month$province_en == p) > 12,\n         logical(1))\n]\ncat(\"Selected provinces:\", length(selected_provinces), \"\\n\")\n\n# Facet titles: how many of the possible months each province reports ---------\nn_possible <- n_distinct(counts_prov_month$month)     # total months in the data (18)\nprov_counts <- counts_prov_month %>%\n  filter(province_en %in% selected_provinces) %>%\n  group_by(province_en) %>%\n  summarise(n_months = n_distinct(month), .groups = \"drop\")\nprov_lab <- setNames(\n  paste0(prov_counts$province_en, \" (\", prov_counts$n_months, \"/\", n_possible, \")\"),\n  prov_counts$province_en\n)\n\nprint(counts_prov_month %>%\n  filter(province_en %in% selected_provinces) %>%\n  ggplot(aes(month, Count)) +\n  geom_line() + geom_point(size = 0.6) +\n  facet_wrap(~ province_en, scales = \"free_y\",\n             labeller = labeller(province_en = prov_lab)) +\n  labs(x = \"date\", y = \"monthly count\") +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 20, hjust = 1)))\n```\n\n::: {.cell-output-display}\n![](session2_climate_data_files/figure-html/part2-province-1.png){fig-align='center' width=1056}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSelected provinces: 18 \n```\n\n\n:::\n:::\n\n\nThe natural next question is whether we could work at a finer spatial scale.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Counts per district per month (finer spatial scale) ---------------------\ncounts_dist_month <- df %>%\n  count(month, district_en, name = \"Count\")\n\n# Would a finer (district) scale work? \nn_months_total <- n_distinct(df$month)                  # 18 possible months\ndist_months <- counts_dist_month %>%\n  group_by(district_en) %>%\n  summarise(n_months = n_distinct(month), .groups = \"drop\")\n\ncat(\"Districts in total:\", nrow(dist_months), \"\\n\")\ncat(\"Districts with >12 months of reported cases:\",\n    sum(dist_months$n_months > 12), \"\\n\")\ncat(\"Provinces with >12 months (from above):\", length(selected_provinces), \"\\n\")\n\n# Share of all reported cases falling in the qualifying districts vs provinces\nok_dist <- dist_months$district_en[dist_months$n_months > 12]\ncat(sprintf(\"The %d qualifying districts hold %.1f%% of all reported cases\\n\",\n            length(ok_dist), 100 * mean(df$district_en %in% ok_dist)))\ncat(sprintf(\"The %d qualifying provinces hold %.1f%% of all reported cases\\n\",\n            length(selected_provinces), 100 * mean(df$province_en %in% selected_provinces)))\n\n# Months of reported cases per province and per district\nprov_months <- counts_prov_month %>%\n  group_by(province_en) %>%\n  summarise(n_months = n_distinct(month), .groups = \"drop\")\n\nmonths_bar <- function(d, unit_label) {\n  ggplot(d, aes(n_months)) +\n    geom_bar(fill = \"steelblue\") +\n    geom_vline(xintercept = 12.5, linetype = \"dashed\", colour = \"red\") +\n    scale_x_continuous(breaks = 1:n_months_total, limits = c(0.5, n_months_total + 0.5)) +\n    labs(y = paste0(\"number of \", unit_label)) +\n    theme_bw()\n}\n\np_prov_freq <- months_bar(prov_months, \"provinces\") +\n  labs(x = NULL, title = \"Provinces by number of months with reported cases\")\np_dist_freq <- months_bar(dist_months, \"districts\") +\n  labs(x = paste0(\"months with reported cases (out of \", n_months_total, \")\"),\n       title = \"Districts by number of months with reported cases\")\n\nprint(p_prov_freq / p_dist_freq)\n```\n\n::: {.cell-output-display}\n![](session2_climate_data_files/figure-html/part2-district-1.png){fig-align='center' width=768}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDistricts in total: 340 \nDistricts with >12 months of reported cases: 37 \nProvinces with >12 months (from above): 18 \nThe 37 qualifying districts hold 90.8% of all reported cases\nThe 18 qualifying provinces hold 97.5% of all reported cases\n```\n\n\n:::\n:::\n\n\n**2.1 How many provinces are reported in the surveillance data, and how many are\nkept after the \"more than 12 months\" filter? Why might we want to restrict to\nprovinces with a longer record before trying to relate cases to climate?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**2.2 Why analyse at the province scale? What do we gain and lose by treating \nthe province as the spatial unit, and what would push you to a finer or coarser \nscale?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**2.3 Look at the per-province panels. Describe the seasonal pattern you see. Do\nall provinces peak at the same time of year? What might explain differences\nbetween provinces?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**2.4 The results column pools *P. vivax* and *P. falciparum* together. Why might\nit matter, for a climate-driven analysis, that these two species are combined?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n<p><input type=\"button\" value=\"Print this page\" onClick=\"window.print()\"></p>\n\n::: {.callout-tip collapse=\"true\"}\n## Solutions for Part 2: click to reveal (try the questions first)\n\n**2.1** There are many provinces in the raw data, but only those reported in more\nthan 12 months are kept (18 provinces kept out of 66), and of those only the ones whose names\nmatch the boundary shapefile are carried forward. Restricting to provinces with a\nlonger record means each province has enough months to show a seasonal signal and to\nstandardise sensibly; provinces with only a handful of reported months cannot support\na climate–seasonality analysis.\n\n**2.2** The spatial unit is a trade-off between signal and sparsity, and the \ncase counts sharpen it. Going finer would likely work, with 90.8% of the malaria \ndata still included. But visualising the 37 districts that clear the \">12 \nmonths\" rule vs the 18 provinces is more difficult. It would also spread almost \nthe same case burden across roughly twice as many units (37 districts versus 18 \nprovinces), so each unit's monthly counts are smaller and noisier, and 303 of \nthe 340 districts are too sparse to use at all. The province scale captures \nnearly all cases (97.5%) in the fewest robust units, and so it is a pragmatic \nchoice. Going finer would suit a focused analysis of the high-burden districts; \ngoing coarser (national) would give complete series but average over very d\nifferent climates and malaria regimes,likely washing out the signal.\n\n**2.3** Most provinces show a seasonal rise and fall, but not all peak in the same\nmonth; malaria seasonality depends on local climate, elevation, land use, and\nthe timing of the rains, which differ across the country. Border provinces and\nforested provinces often behave differently from central ones.\n\n**2.4** *P. vivax* and *P. falciparum* differ in incubation period, in relapse\nbehaviour (vivax can relapse from liver-stage hypnozoites months later), and\nlikely in their climate sensitivity. But they have similar mosquito vectors. So\nwhether or not pooling them means blurring the climate-malaria signal depends on\nhow climate-related those factors are, and whether the mosquito relationship \nwith climate would dominate. A potential future direction to explore. \n:::\n\n---\n\n# **Part 3:** Environmental variables (reanalysis)\n\n::: speaker-note\nThis part links gridded climate to the administrative units that malaria is\nreported in. The conceptual step to draw out is the *spatial mismatch*: climate\ncomes on a regular latitude–longitude grid, but cases come per province. We\nresolve it in two steps. First, **strict cell-centre assignment**: a grid cell\nbelongs to the province whose polygon contains the cell's *centre* (a\npoint-in-polygon test, matching the `regionmask` package). Second, the province's\ncells are combined with an **area-weighted average**, each cell weighted by cos of\nits latitude because grid cells shrink towards the poles; this is the standard\nspatial mean (see the aside on population weighting).\nParticipants often ask why we keep temperature in Kelvin during standardisation:\nbecause a constant offset (Kelvin vs Celsius) does not change a standardised\n(z-scored) series, so it only matters for the plots, where we convert to °C.\n:::\n\nMalaria is reported per province, but ERA5 climate comes on a regular grid. To\nlink them, we summarise the grid to provinces in two steps: **strict cell-centre\nassignment**, where each grid cell is assigned to the province whose polygon contains\nthe cell's centre (a point-in-polygon test with `sf`, matching the\n[`regionmask`](https://regionmask.readthedocs.io){target=\"_blank\"} package), and then\nan **area-weighted average** of those cells, weighting each by cos of its latitude so\nthat cells count in proportion to their area.\n\n::: {.callout-note collapse=\"true\"}\n## Why cos of latitude is the exact area weight\n\nOn a regular grid every cell spans the same number of degrees in latitude and\nlongitude, but equal degrees are not equal area: meridians converge towards the\npoles, so a cell's east-west width shrinks with latitude while its north-south height\nstays fixed. The area of the cell between latitudes `lat₁` and `lat₂`, over a\nlongitude span `Δλ` on a sphere of radius `R`, is\n`A = R² · Δλ · (sin(lat₂) - sin(lat₁))`. For a cell of height `Δlat` centred at\nlatitude `lat`, the identity\n`sin(lat + Δlat/2) - sin(lat - Δlat/2) = 2 · cos(lat) · sin(Δlat/2)` turns this into\n`A = R² · Δλ · 2 · sin(Δlat/2) · cos(lat)`. Every factor except `cos(lat)` is\nidentical for all cells on a regular grid, and constant factors cancel in a\nnormalised weighted mean, so weighting each cell by cos of its centre latitude\nreproduces the true area weighting exactly. It is not a small-angle approximation: it\nis exact for a sphere. The Earth's slight oblateness shifts cell areas by a fraction\nof a percent, far below anything that matters at this provincial scale.\n:::\n\n::: {.callout-note appearance=\"minimal\"}\nWe weight each cell by its area (cos of latitude), the standard spatial mean. For\nclimate and health work an even better choice is **population-density weighting**,\nwhich captures the climate where people actually live. That matters most for\ncountries with very uneven populations (for example Australia, where most people are\nconcentrated in a few coastal cities); at Thailand's provincial scale the difference\nis small, so we keep area-weighting here.\n:::\n\n**Run the code below, then work through the questions.**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(terra)\n\n# Province (ADM1) boundaries ----------------------------------------------\nshape_file <- st_read(\n  file.path(data_dir, \"shape_files\",\n            \"tha_admbnda_adm1_rtsd_20190221\",\n            \"tha_admbnda_adm1_rtsd_20190221.shp\"),\n  quiet = TRUE\n)\nregion_names <- shape_file$ADM1_EN\ncat(\"Number of provinces in shapefile:\", length(region_names), \"\\n\")\n\n# The surveillance province names must match the shapefile's ADM1_EN names to be\n# mapped. Keep only the selected provinces that are present in the boundaries\n# (mirrors the original workflow, which reduces the province list to those found\n# in the shapefile). Report any that are dropped so name mismatches are visible.\nmissing <- setdiff(selected_provinces, region_names)\nif (length(missing))\n  message(\"Provinces not matched in shapefile and dropped: \",\n          paste(missing, collapse = \", \"))\nselected_provinces <- selected_provinces[selected_provinces %in% region_names]\ncat(\"Provinces carried forward (matched to boundaries):\",\n    length(selected_provinces), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of provinces in shapefile: 77 \nProvinces carried forward (matched to boundaries): 15 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ERA5 monthly reanalysis: 2 m temperature (2t -> t2m) and precip (tp) -----\n# One netCDF file per month; sorting the file paths puts them in time order.\ntas_files <- sort(list.files(\n  file.path(data_dir, \"reanalysis\", \"monthly-averaged\", \"2t\"),\n  pattern = \"\\\\.nc$\", recursive = TRUE, full.names = TRUE))\npr_files <- sort(list.files(\n  file.path(data_dir, \"reanalysis\", \"monthly-averaged\", \"tp\"),\n  pattern = \"\\\\.nc$\", recursive = TRUE, full.names = TRUE))\n\ntas_r <- rast(tas_files)   # temperature, one layer per month (Kelvin)\npr_r  <- rast(pr_files)    # total precipitation, one layer per month (metres)\n\n# Restrict to the Thailand region used in the original workflow\nregion_ext <- ext(97, 108, 5, 22)\ntas_r <- crop(tas_r, region_ext)\npr_r  <- crop(pr_r,  region_ext)\n\n# Recover the month for each layer from the filename (YYYYMMDD-...)\nmonth_from_file <- function(f)\n  floor_date(as.Date(sub(\".*_(\\\\d{8})-\\\\d{8}\\\\.nc$\", \"\\\\1\", basename(f)),\n                     format = \"%Y%m%d\"), \"month\")\nclim_months <- month_from_file(tas_files)\ncat(\"Reanalysis covers\", length(clim_months), \"months:\",\n    format(min(clim_months)), \"to\", format(max(clim_months)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReanalysis covers 15 months: 2025-01-01 to 2026-03-01 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Map of the time-mean temperature and rainfall over the region -----------\ntas_mean_c <- mean(tas_r) - 273.15          # Kelvin -> Celsius for display\npr_mean    <- mean(pr_r)\n\nmap_df_t <- as.data.frame(tas_mean_c, xy = TRUE); names(map_df_t)[3] <- \"value\"\nmap_df_r <- as.data.frame(pr_mean,    xy = TRUE); names(map_df_r)[3] <- \"value\"\n\nm_t <- ggplot(map_df_t, aes(x, y, fill = value)) +\n  geom_raster() +\n  geom_sf(data = shape_file, fill = NA, colour = \"grey30\",\n          linewidth = 0.2, inherit.aes = FALSE) +\n  scale_fill_viridis_c(name = \"°C\") +\n  coord_sf(expand = FALSE) +\n  labs(title = \"Mean temperature\", x = \"lon\", y = \"lat\") +\n  theme_bw()\n\nm_r <- ggplot(map_df_r, aes(x, y, fill = value)) +\n  geom_raster() +\n  geom_sf(data = shape_file, fill = NA, colour = \"grey30\",\n          linewidth = 0.2, inherit.aes = FALSE) +\n  scale_fill_viridis_c(name = \"m\", option = \"mako\") +\n  coord_sf(expand = FALSE) +\n  labs(title = \"Mean rainfall\", x = \"lon\", y = \"lat\") +\n  theme_bw()\n\nm_t + m_r\n```\n\n::: {.cell-output-display}\n![](session2_climate_data_files/figure-html/part3-maps-1.png){fig-align='center' width=1056}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Assign each grid cell to a province by STRICT CELL-CENTRE assignment --------\n# A cell belongs to the province whose polygon contains the cell's *centre*, and\n# the provincial value is the simple mean over those cells. This reproduces the\n# standard Python geospatial workflow used in the original analysis (the\n# `regionmask` package), rather than relying on the raster library's own polygon\n# extraction, whose boundary handling can differ slightly.\ngrid_xy  <- terra::xyFromCell(tas_r, seq_len(terra::ncell(tas_r)))\ngrid_pts <- sf::st_as_sf(as.data.frame(grid_xy), coords = c(\"x\", \"y\"),\n                         crs = sf::st_crs(shape_file))\nwithin   <- sf::st_within(grid_pts, shape_file)          # cell centre in polygon?\ncell_region <- vapply(within,\n                      function(h) if (length(h)) h[1] else NA_integer_,\n                      integer(1))\n\n# Provincial mean for every layer (time step), area-weighted by cell size. Grid\n# cells shrink towards the poles, so each cell is weighted by cos(latitude); this is\n# the standard, physically correct spatial average. The cell assignment and weights\n# are shared by the reanalysis and (after resampling) the CMIP data, so they are\n# reused in Part 4.\ncell_w <- cos(grid_xy[, 2] * pi / 180)                    # per-cell area weight (cos latitude)\nregion_means <- function(r) {\n  vals <- terra::values(r)                                # ncell x nlayer\n  out  <- matrix(NA_real_, length(region_names), ncol(vals),\n                 dimnames = list(region_names, NULL))\n  for (k in seq_along(region_names)) {\n    sel <- which(cell_region == k)\n    if (!length(sel)) next\n    w <- cell_w[sel]\n    out[k, ] <- colSums(vals[sel, , drop = FALSE] * w, na.rm = TRUE) / sum(w)\n  }\n  out\n}\n\ntas_prov <- region_means(tas_r)\npr_prov  <- region_means(pr_r)\n\n# Tidy into long tables, keeping only the selected provinces\nto_long <- function(mat, value_name) {\n  m <- as.matrix(mat)\n  rownames(m) <- region_names\n  colnames(m) <- as.character(clim_months)\n  as.data.frame(m) %>%\n    tibble::rownames_to_column(\"province_en\") %>%\n    pivot_longer(-province_en, names_to = \"month\", values_to = value_name) %>%\n    mutate(month = as.Date(month))\n}\n\nclim_long <- to_long(tas_prov, \"temp_k\") %>%\n  left_join(to_long(pr_prov, \"rain_m\"), by = c(\"province_en\", \"month\")) %>%\n  mutate(temp_c = temp_k - 273.15) %>%\n  filter(province_en %in% selected_provinces)\n\nprint(head(clim_long))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  province_en month      temp_k     rain_m temp_c\n  <chr>       <date>      <dbl>      <dbl>  <dbl>\n1 Bangkok     2025-01-01   298. 0.00000870   24.8\n2 Bangkok     2025-02-01   301. 0.00134      27.8\n3 Bangkok     2025-03-01   303. 0.00123      29.5\n4 Bangkok     2025-04-01   304. 0.00251      30.6\n5 Bangkok     2025-05-01   303. 0.00728      29.6\n6 Bangkok     2025-06-01   303. 0.00336      30.0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Per-province monthly temperature and rainfall series --------------------\nprint(ggplot(clim_long, aes(month, temp_c)) +\n  geom_line() + geom_point(size = 0.5) +\n  facet_wrap(~ province_en, scales = \"free_y\") +\n  labs(x = \"date\", y = \"monthly mean temperature (°C)\") +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 20, hjust = 1)))\n```\n\n::: {.cell-output-display}\n![](session2_climate_data_files/figure-html/part3-series-1.png){fig-align='center' width=1056}\n:::\n:::\n\n\n**3.1 We averaged climate over each province. What information do we lose by\ndoing this? For a large province with varied terrain, is a single provincial\naverage a good summary of the climate that mosquitoes and people experience?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**3.2 Look at the per-province temperature series. How large is the within-year\ntemperature range compared to the differences between provinces? Which do you\nthink will be more useful for explaining malaria seasonality?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**3.3 The reanalysis only covers a couple of years here. What are the risks of\nlearning a climate–malaria relationship from such a short record?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n<p><input type=\"button\" value=\"Print this page\" onClick=\"window.print()\"></p>\n\n::: {.callout-tip collapse=\"true\"}\n## Solutions for Part 3: click to reveal (try the questions first)\n\n**3.1** Averaging to a province discards all within-province spatial variation:\nelevation gradients, forest edges, urban vs rural. For a large or topographically\nvaried province, a single average may not represent the conditions where\ntransmission actually happens (often specific ecological niches), so the link to\ncases is weakened.\n\n**3.2** Typically the within-year (seasonal) temperature swing within a province is\nmodest compared with, say, rainfall seasonality, and provinces differ from each\nother too. Both the seasonal cycle and the between-province contrasts carry\ninformation; the panel model in Part 5 uses both by standardising within province\nand pooling across provinces.\n\n**3.3** A short record risks fitting to year-specific anomalies (an unusual season,\na one-off outbreak) rather than a stable climate–malaria relationship, and gives\nvery little power to separate climate effects from other drivers. Projections built\non such a fit should be treated as illustrative.\n:::\n\n---\n\n# **Part 4:** Future climate projections (CMIP6)\n\n::: speaker-note\nThis part summarises the CMIP6 multi-model ensemble to the same provinces, under\ntwo scenarios. The key ideas for participants: (1) CMIP6 is an *ensemble* of many\nclimate models; we summarise across models with a mean and an interquartile band,\nrather than trusting any single model; and (2) the two scenarios (SSP1-2.6 low\nemissions, SSP5-8.5 high emissions) bracket a range of plausible futures. This is\na direct translation of the original Python, including the precipitation unit\nconversion. It is the heaviest step in the document; on a slow machine give it a\nminute, and note that `freeze: auto` caches it afterwards.\n:::\n\nThe learned relationship (Part 5) is only useful if we can apply it to the future.\nCMIP6 provides projections of temperature (`tas`) and precipitation (`pr`) from\nmany climate models, under different emissions scenarios. We summarise them to the\nsame provinces, under two scenarios: **SSP1-2.6** (low emissions) and **SSP5-8.5**\n(high emissions).\n\n**Run the code below, then work through the questions.**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ncdf4)\n\ncmip_dir <- file.path(data_dir, \"cmip6\", \"monthly-averaged\")\ncmip_files <- list(\n  ssp126_tas = \"cmip6_regrided_model_ensemble.Thai_region.ssp126.tas.nc\",\n  ssp585_tas = \"cmip6_regrided_model_ensemble.Thai_region.ssp585.tas.nc\",\n  ssp126_pr  = \"cmip6_regrided_model_ensemble.Thai_region.ssp126.pr.nc\",\n  ssp585_pr  = \"cmip6_regrided_model_ensemble.Thai_region.ssp585.pr.nc\"\n)\n\n# Read one CMIP variable as a list of per-model SpatRasters (time layers),\n# returning the models, times, and the raster grid. Dimensions are read by\n# name so the code does not depend on storage order.\nread_cmip_var <- function(path, var, from_date = NULL) {\n  nc  <- nc_open(path)\n  on.exit(nc_close(nc))\n  lon <- ncvar_get(nc, \"lon\"); lat <- ncvar_get(nc, \"lat\")\n  tim <- ncvar_get(nc, \"time\")\n  models <- ncvar_get(nc, \"model\")\n  # time units -> dates\n  tunits <- ncatt_get(nc, \"time\", \"units\")$value\n  origin <- as.Date(sub(\".*since \", \"\", tunits))\n  dates  <- floor_date(origin + tim, \"month\")\n  arr <- ncvar_get(nc, var)                       # dims in file order\n  dn  <- sapply(nc$var[[var]]$dim, function(d) d$name)\n  # reorder to lon, lat, time, model\n  perm <- match(c(\"lon\", \"lat\", \"time\", \"model\"), dn)\n  arr <- aperm(arr, perm)\n  # Trim to the reanalysis start onwards (as in the original workflow), so the\n  # historical fit and the future projection share the same start month.\n  if (!is.null(from_date)) {\n    keep <- dates >= from_date\n    arr  <- arr[, , keep, , drop = FALSE]\n    dates <- dates[keep]\n  }\n  list(arr = arr, lon = lon, lat = lat, dates = dates, models = models)\n}\n\ncmip_start <- min(clim_months)   # reanalysis start month\ntas126 <- read_cmip_var(file.path(cmip_dir, cmip_files$ssp126_tas), \"tas\", cmip_start)\ncat(\"CMIP6 grid:\", length(tas126$lon), \"lon x\", length(tas126$lat), \"lat;\",\n    length(tas126$models), \"models;\", length(tas126$dates), \"months\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCMIP6 grid: 12 lon x 19 lat; 45 models; 912 months\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Build a raster template on the reanalysis grid so CMIP can be interpolated\n# onto it (matching the original workflow), then averaged per province.\nref_grid <- tas_r[[1]]        # reanalysis grid (already cropped to region)\n\n# Interpolate a per-model, per-time CMIP array onto the reanalysis grid and\n# average over each province. Returns a tidy data frame of provincial means.\n# Build a north-up, multi-layer SpatRaster from one model's [lon, lat, time]\n# slice. Handles either coordinate ordering and treats the lon/lat values as\n# cell centres (so the extent is padded by half a cell each side).\nslice_to_rast <- function(slc, lon, lat, ref) {\n  lon_o <- order(lon); lat_o <- order(lat)          # index ascending\n  slc <- slc[lon_o, lat_o, , drop = FALSE]          # lon asc, lat asc\n  a <- aperm(slc, c(2, 1, 3))                        # -> lat x lon x time\n  a <- a[dim(a)[1]:1, , , drop = FALSE]              # flip: north (max lat) = row 1\n  r <- rast(a)                                       # 3rd dim -> layers\n  lo <- sort(lon); la <- sort(lat)\n  dx <- mean(diff(lo)); dy <- mean(diff(la))\n  ext(r) <- c(min(lo) - dx/2, max(lo) + dx/2,\n              min(la) - dy/2, max(la) + dy/2)\n  crs(r) <- crs(ref)                                 # match the reanalysis grid\n  r\n}\n\n# Interpolate every model's CMIP slice onto the reanalysis grid and average per\n# province, KEEPING the per-model detail (province x month x model). We keep the\n# per-model array because the Part 6 projection needs the model spread, not just\n# the ensemble mean.\ncmip_provincial_bymodel <- function(cv, var, ref, provinces) {\n  nm <- length(cv$models)\n  # Optional speed/debug knob: set env var CMIP_MODEL_CAP to a small integer to\n  # use only the first few models (much faster). Unset / 0 uses all models.\n  cap <- suppressWarnings(as.integer(Sys.getenv(\"CMIP_MODEL_CAP\", \"\")))\n  if (!is.na(cap) && cap > 0) nm <- min(nm, cap)\n  out <- vector(\"list\", nm)\n  for (m in seq_len(nm)) {\n    slc <- cv$arr[, , , m]                     # lon x lat x time\n    r <- slice_to_rast(slc, cv$lon, cv$lat, ref)\n    names(r) <- as.character(cv$dates)\n    if (var == \"pr\") r <- r * 86400 / 1000     # flux (kg m-2 s-1) -> m (as in original)\n    else             r <- r - 273.15           # Kelvin -> Celsius\n    r <- resample(r, ref, method = \"bilinear\") # interpolate onto reanalysis grid\n    pm <- region_means(r)                       # strict cell-centre assignment (as Part 3)\n    out[[m]] <- pm[provinces, , drop = FALSE]\n  }\n  arr3 <- simplify2array(out)                  # province x month x model\n  list(arr = arr3, dates = cv$dates, provinces = provinces)\n}\n\n# Ensemble summary (mean + interquartile band) from a per-model array.\nsummarise_cmip <- function(bm, scenario, var) {\n  arr3 <- bm$arr; nt <- length(bm$dates)\n  qf <- function(p) as.vector(apply(arr3, c(1, 2), quantile, probs = p, na.rm = TRUE))\n  data.frame(\n    province_en = rep(bm$provinces, times = nt),\n    month       = rep(bm$dates, each = length(bm$provinces)),\n    scenario = scenario, variable = var,\n    mean = as.vector(apply(arr3, c(1, 2), mean, na.rm = TRUE)),\n    q25 = qf(0.25), q75 = qf(0.75)\n  )\n}\n```\n:::\n\n\n::: {.todo-note}\nThe CMIP6 interpolation-and-averaging above is the single heaviest step and the\npart most likely to need a check on first render (it reads a 45-model ensemble and\nresamples it onto the reanalysis grid, exactly as the original Python did). If it\nis too slow for a live session, the course team may wish to pre-compute the\nprovincial summaries once and cache them. It is left as a direct port here so the\nmethod is transparent.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntas585 <- read_cmip_var(file.path(cmip_dir, cmip_files$ssp585_tas), \"tas\", cmip_start)\npr126  <- read_cmip_var(file.path(cmip_dir, cmip_files$ssp126_pr),  \"pr\",  cmip_start)\npr585  <- read_cmip_var(file.path(cmip_dir, cmip_files$ssp585_pr),  \"pr\",  cmip_start)\n\n# Restrict all four files to the CLIMATE MODELS they have in common, in the same\n# order (as the original workflow does). The files hold different numbers of\n# models, and the projection pairs temperature and rainfall model-by-model, so\n# they must refer to the same models in the same order.\ncommon_models <- sort(Reduce(intersect,\n  list(tas126$models, tas585$models, pr126$models, pr585$models)))\nalign_models <- function(cv) {\n  idx <- match(common_models, cv$models)\n  cv$arr    <- cv$arr[, , , idx, drop = FALSE]\n  cv$models <- common_models\n  cv\n}\ntas126 <- align_models(tas126); tas585 <- align_models(tas585)\npr126  <- align_models(pr126);  pr585  <- align_models(pr585)\ncat(\"CMIP models in common across all four files:\", length(common_models), \"\\n\")\n\n# Per-model provincial climate (kept for the Part 6 projection)\ncmip_tas <- list(\n  \"SSP1-2.6\" = cmip_provincial_bymodel(tas126, \"tas\", ref_grid, selected_provinces),\n  \"SSP5-8.5\" = cmip_provincial_bymodel(tas585, \"tas\", ref_grid, selected_provinces))\ncmip_pr <- list(\n  \"SSP1-2.6\" = cmip_provincial_bymodel(pr126, \"pr\", ref_grid, selected_provinces),\n  \"SSP5-8.5\" = cmip_provincial_bymodel(pr585, \"pr\", ref_grid, selected_provinces))\n\n# Ensemble summary for plotting\ncmip_summary <- bind_rows(\n  summarise_cmip(cmip_tas[[\"SSP1-2.6\"]], \"SSP1-2.6\", \"tas\"),\n  summarise_cmip(cmip_tas[[\"SSP5-8.5\"]], \"SSP5-8.5\", \"tas\"),\n  summarise_cmip(cmip_pr[[\"SSP1-2.6\"]],  \"SSP1-2.6\", \"pr\"),\n  summarise_cmip(cmip_pr[[\"SSP5-8.5\"]],  \"SSP5-8.5\", \"pr\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCMIP models in common across all four files: 41 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Annual means for a clearer long-range view, for one example province -----\nexample_province <- selected_provinces[1]\n\nannual <- cmip_summary %>%\n  mutate(year = year(month)) %>%\n  filter(province_en == example_province) %>%\n  group_by(province_en, scenario, variable, year) %>%\n  summarise(mean = mean(mean), q25 = mean(q25), q75 = mean(q75), .groups = \"drop\")\n\nlab <- c(tas = \"temperature (°C)\", pr = \"total precipitation (m)\")\n\nprint(ggplot(annual, aes(year, mean, colour = scenario, fill = scenario)) +\n  geom_ribbon(aes(ymin = q25, ymax = q75), alpha = 0.2, colour = NA) +\n  geom_line(linewidth = 0.8) +\n  facet_wrap(~ variable, scales = \"free_y\",\n             labeller = labeller(variable = lab)) +\n  scale_colour_manual(values = c(\"SSP1-2.6\" = \"#2166ac\", \"SSP5-8.5\" = \"#b2182b\")) +\n  scale_fill_manual(values   = c(\"SSP1-2.6\" = \"#2166ac\", \"SSP5-8.5\" = \"#b2182b\")) +\n  labs(x = \"year\", y = NULL,\n       title = paste0(\"CMIP6 projections for \", example_province),\n       subtitle = \"Model mean (line) and interquartile range (band)\") +\n  theme_bw())\n```\n\n::: {.cell-output-display}\n![](session2_climate_data_files/figure-html/part4-plot-1.png){fig-align='center' width=1056}\n:::\n:::\n\n\n**4.1 The projections are shown as a model mean with an interquartile band. Why do\nwe show a *range* across models rather than picking the single \"best\" model?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**4.2 Compare the two scenarios (SSP1-2.6 and SSP5-8.5). How far apart are the\ntemperature projections by the end of the century? What about rainfall: is the\nmodel agreement as strong?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**4.3 We are about to feed these projections into a malaria model that was fitted\non only a couple of years of reanalysis. What assumption are we making about the\nclimate–malaria relationship when we extrapolate it decades into the future?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n<p><input type=\"button\" value=\"Print this page\" onClick=\"window.print()\"></p>\n\n::: {.callout-tip collapse=\"true\"}\n## Solutions for Part 4: click to reveal (try the questions first)\n\n**4.1** Individual climate models disagree, especially on rainfall. The\nensemble mean is more reliable than any single model, and the spread (here the\ninterquartile band) is itself the honest expression of projection *uncertainty*.\nPicking one \"best\" model hides that uncertainty.\n\n**4.2** Temperature projections usually diverge clearly between the two scenarios\nby late century, with SSP5-8.5 substantially warmer, and models tend to agree on\nthe direction of warming. Rainfall is far less certain: the inter-model band is\nusually wide and the scenarios may overlap, reflecting genuine disagreement about\nhow precipitation will change.\n\n**4.3** We are assuming the climate–malaria relationship learned over a couple of\nrecent years holds, unchanged, decades into the future, i.e. that no adaptation,\nintervention, land-use change, drug resistance, or shift in the mosquito/parasite\nsystem alters it. That is a strong assumption and the main caveat on any such\nprojection.\n:::\n\n---\n\n# **Part 5:** Fitting climate to incidence\n\n::: speaker-note\nThis is the core of the session: a statistical model relating climate to malaria\ncases across all provinces at once (a \"panel\" model). The design choices to draw\nout: (1) we model the *first difference* (month-to-month change) in cases rather\nthan the level, and we *standardise* per province, so that provinces of very\ndifferent sizes contribute comparably; (2) climate enters as temperature, rainfall,\nand their squares, allowing a hump-shaped (optimum) response; and (3) the fitted\ncoefficients are *shared* across provinces, one climate–malaria relationship\napplied everywhere. This is a direct translation of the original \"panel method\"\nordinary-least-squares fit. Frame it explicitly as the *simplest* model, one set\nof coefficients for the whole country. Part 6 then pushes it forward under CMIP6 to\nproject future cases; the optional SEIRS section at the end of this session is the\nmore scientifically sound alternative (per-province transmission) for those who want\na mechanistic model.\n:::\n\nWe now link climate to cases directly with a simple statistical model, pooling all\nprovinces. We use a **panel method**, the same approach used to learn the impact\nof temperature and rainfall on the gross domestic product of the world's economies\n([Burke, Hsiang & Miguel, *Nature*, 2015](https://www.nature.com/articles/nature15725){target=\"_blank\"})\n, but here applied to learn the impact of temperature and rainfall on the\nmonth-to-month *change* in infection count. Because these simple panel methods\ncannot account for trends, we first remove the trend by taking the first difference,\nthen standardise each province by its own mean and standard deviation over time.\nTemperature and rainfall enter as themselves and squared, allowing a non-linear\n(hump-shaped) response, with one shared relationship across provinces. Because we\nmodel the first difference (the \"integrated\" step) and reconstruct the level by a\ncumulative sum, this is an **ARIMA-style** model, more precisely an autoregressive\nmodel with exogenous inputs (ARX), with temperature and rainfall as the exogenous\nclimate drivers (hence `arx_fit` below).\n\nThis is perhaps the most basic model one can build, and is designed to illustrate\nthe logic of integrating the climate data. It uses a single set of coefficients for\nall provinces. In Part 6 we push this fitted model forward under the CMIP6 climate\nto project future cases. The optional SEIRS section at the end of this session is\nmore scientifically sound (it has per-province transmission) and gives you a code\nbase for fitting a transmission model directly.\n\n**Run the code below, then work through the questions.**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Align cases and climate on the same province x month grid ----------------\nprovinces <- selected_provinces\nmonths    <- sort(unique(clim_long$month))\n\n# Case matrix: provinces x months, zero-filled where no cases were reported\ncases_mat <- counts_prov_month %>%\n  filter(province_en %in% provinces) %>%\n  complete(province_en = provinces, month = months, fill = list(Count = 0)) %>%\n  filter(month %in% months) %>%\n  arrange(province_en, month) %>%\n  pivot_wider(names_from = month, values_from = Count) %>%\n  tibble::column_to_rownames(\"province_en\") %>%\n  as.matrix()\ncases_mat <- cases_mat[provinces, , drop = FALSE]\n\n# Climate matrices on the same grid\nmat_from_long <- function(var) {\n  clim_long %>%\n    select(province_en, month, all_of(var)) %>%\n    pivot_wider(names_from = month, values_from = all_of(var)) %>%\n    tibble::column_to_rownames(\"province_en\") %>%\n    as.matrix() %>% `[`(provinces, , drop = FALSE)\n}\nclim_temp <- mat_from_long(\"temp_k\")   # Kelvin (offset irrelevant once standardised)\nclim_rain <- mat_from_long(\"rain_m\")\n\ncat(\"cases:\", nrow(cases_mat), \"provinces x\", ncol(cases_mat), \"months;\",\n    \"total cases =\", sum(cases_mat), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncases: 15 provinces x 15 months; total cases = 12829 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Standardise per province ------------------------------------------------\n# Use the population standard deviation (divide by n, not n-1) to match NumPy's\n# np.std in the original workflow. R's built-in sd() uses n-1, which would shift\n# the standardisation and change the fitted coefficients.\npopsd <- function(x) sqrt(mean((x - mean(x))^2))\n\n# Response: standardised first difference of cases, per province\ncases_fd <- cases_mat[, -1] - cases_mat[, -ncol(cases_mat)]\nfd_mean  <- rowMeans(cases_fd)\nfd_sd    <- apply(cases_fd, 1, popsd)\nz_cases_fd <- (cases_fd - fd_mean) / fd_sd\n\n# Predictors: standardised temperature and rainfall, per province\nz_temp <- (clim_temp - rowMeans(clim_temp)) / apply(clim_temp, 1, popsd)\nz_rain <- (clim_rain - rowMeans(clim_rain)) / apply(clim_rain, 1, popsd)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Ordinary least squares on the pooled (flattened) panel ------------------\n# Predictors are temperature, temperature^2, rainfall, rainfall^2, using the\n# months aligned with the first differences (drop the first month).\nY <- as.vector(z_cases_fd)\nzt <- z_temp[, -1]; zr <- z_rain[, -1]\nX  <- cbind(as.vector(zt), as.vector(zt)^2, as.vector(zr), as.vector(zr)^2)\n\n# Centre (as in the original), solve, and predict\nY_mean <- mean(Y);            Y_prime <- Y - Y_mean\nX_mean <- colMeans(X);        X_prime <- sweep(X, 2, X_mean)\nbeta   <- solve(t(X_prime) %*% X_prime, t(X_prime) %*% Y_prime)\nY_hat  <- as.vector(X_prime %*% beta) + Y_mean\n\ncolnames(X) <- c(\"temp\", \"temp^2\", \"rain\", \"rain^2\")\nprint(round(setNames(as.vector(beta), colnames(X)), 3))\n\n# Reshape prediction back to province x month, and rebuild case counts by\n# reversing the standardisation and the first-differencing (cumulative sum).\nz_hat <- matrix(Y_hat, nrow = nrow(z_cases_fd))\nfitted_cases <- cases_mat * 0\nfor (i in seq_len(nrow(cases_mat))) {\n  fitted_cases[i, 1]  <- cases_mat[i, 1]\n  fitted_cases[i, -1] <- fitted_cases[i, 1] +\n    cumsum(z_hat[i, ] * fd_sd[i] + fd_mean[i])\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  temp temp^2   rain rain^2 \n 0.241  0.295  0.096 -0.076 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Observed vs fitted monthly cases, per province --------------------------\nfit_long <- bind_rows(\n  as.data.frame(cases_mat) %>% tibble::rownames_to_column(\"province_en\") %>%\n    pivot_longer(-province_en, names_to = \"month\", values_to = \"cases\") %>%\n    mutate(series = \"observed\"),\n  as.data.frame(fitted_cases) %>% tibble::rownames_to_column(\"province_en\") %>%\n    pivot_longer(-province_en, names_to = \"month\", values_to = \"cases\") %>%\n    mutate(series = \"fitted\")\n) %>% mutate(month = as.Date(month))\n\nprint(ggplot(fit_long, aes(month, cases, colour = series)) +\n  geom_line(linewidth = 0.6) +\n  facet_wrap(~ province_en, scales = \"free_y\") +\n  scale_colour_manual(values = c(observed = \"black\", fitted = \"red\")) +\n  labs(x = \"date\", y = \"monthly cases\",\n       title = \"Observed vs panel-fitted monthly cases\") +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 20, hjust = 1)))\n```\n\n::: {.cell-output-display}\n![](session2_climate_data_files/figure-html/part5-diag-1.png){fig-align='center' width=1056}\n:::\n:::\n\n\nThe fitted `beta` coefficients define the climate response. In **Part 6** we apply\nthem to the future CMIP6 climate to project cases forward.\n\n**5.1 The model uses temperature, temperature², rainfall, and rainfall². What\nshape of climate–malaria relationship do the squared terms allow that a\nstraight-line model could not? Why is that biologically sensible for a\nmosquito-borne disease?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**5.2 We standardised cases and climate *per province* before pooling. What would\ngo wrong if we pooled the raw counts across provinces without standardising?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**5.3 Look at the observed-vs-fitted panels. Where does the model do well, and\nwhere does it do poorly? What might it be missing (think about what drives malaria\nbesides climate)?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**5.4 To project future cases, we would apply these fitted coefficients to the\nCMIP6 climate from Part 4. List one thing you would want to check about the future\nclimate values before trusting such a projection.**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n<p><input type=\"button\" value=\"Print this page\" onClick=\"window.print()\"></p>\n\n::: {.callout-tip collapse=\"true\"}\n## Solutions for Part 5: click to reveal (try the questions first)\n\n**5.1** The squared terms allow a *hump-shaped* (unimodal) response: cases rising\nwith temperature or rainfall up to an optimum and then falling. This is\nbiologically sensible because mosquito survival, biting, and parasite development\neach have thermal optima, and both drought and flushing rains can reduce breeding,\nso the response to climate is rarely monotonic.\n\n**5.2** Provinces differ enormously in population and case numbers. Pooling raw\ncounts would let a few large-caseload provinces dominate the fit, and would confound\n\"more cases because bigger\" with \"more cases because of climate\". Standardising per\nprovince puts every province on a comparable footing so the shared coefficients\nreflect the climate relationship, not province size.\n\n**5.3** The model tends to capture the broad seasonal rise and fall but misses\nsharp peaks, sudden outbreaks, and province-specific idiosyncrasies. Malaria is\nalso driven by non-climate factors: interventions (bed nets, spraying), human\nmovement and importation, drug resistance, health-system reporting changes, none\nof which are in a climate-only model.\n\n**5.4** Sensible checks include: are the future climate values within the range the\nmodel was trained on (extrapolation beyond the training range is dangerous)? Are the\nunits and standardisation applied identically to the projections? Is the seasonal\nstructure of the projections realistic? Does the province averaging match?\n:::\n\n---\n\n# **Part 6:** Projecting future cases (statistical model)\n\n::: speaker-note\nThis is the pay-off: we take the model fitted on the historical period (Part 5) and\npush it forward under the CMIP6 climate (Part 4) to project future cases. The\nmechanics: standardise each future climate value using the *historical*\nper-province mean and standard deviation (never re-standardise on the future data,\nor you throw away the trend you are trying to project), apply the fitted `beta`, and\nrebuild case counts. We run every climate model separately and show the ensemble\nmean and interquartile band, exactly as we did for the raw climate in Part 4.\n\nBe sure to make the key caveat explicit (see the warning box): reconstructing counts\nby cumulatively summing predicted month-to-month changes over ~75 years behaves like\na random walk and will drift. This is a genuine limitation of projecting a\ndifferenced/ARX model far ahead, and a large part of *why* one might prefer a bounded\nmechanistic model (the optional SEIRS section at the end of this session) for long\nhorizons. Treat the projection as illustrative of method, not as a forecast.\n:::\n\nWe now push the fitted model forward. For each climate model and scenario, we\nstandardise the future CMIP6 temperature and rainfall using the **historical**\nper-province mean and standard deviation (the same scaling the model was fitted\nwith), apply the fitted coefficients to get the predicted month-to-month change in\ncases, and rebuild counts by cumulative sum, seeding from the last observed month.\n\n::: {.callout-warning}\n## A projection, not a forecast\nRebuilding case counts by cumulatively summing predicted monthly *changes* over\ndecades behaves like a random walk and will drift, so the absolute numbers far into\nthe future should not be read literally. This is an inherent limitation of pushing a\nfirst-difference (ARX) model a long way forward, and is one reason a bounded\nmechanistic model (the optional SEIRS section at the end of this session) is often\npreferred for long-range projection. Use this to see *how* climate projections feed\na fitted model, not as a prediction of future case counts.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Historical per-province climate scaling, in the SAME units as the CMIP arrays\n# (temperature in °C, rainfall in m). Standardising is unaffected by a constant\n# offset, so these reproduce the scaling used to fit the model in Part 5.\ntemp_mean_p <- rowMeans(clim_temp) - 273.15   # clim_temp is Kelvin; CMIP tas is °C\ntemp_sd_p   <- apply(clim_temp, 1, popsd)\nrain_mean_p <- rowMeans(clim_rain)\nrain_sd_p   <- apply(clim_rain, 1, popsd)\n\nlast_obs <- cases_mat[, ncol(cases_mat)]      # seed the projection at the last observed month\nhist_end <- max(months)\n\n# Apply the fitted ARX model to one climate model's future climate, rebuild counts.\nproject_one <- function(tas_pm, pr_pm, dates) {\n  zt <- (tas_pm - temp_mean_p) / temp_sd_p    # province x month (vectors recycle per row)\n  zr <- (pr_pm  - rain_mean_p) / rain_sd_p\n  yhat <- (zt   - X_mean[1]) * beta[1] +      # predicted standardised first-difference\n          (zt^2 - X_mean[2]) * beta[2] +\n          (zr   - X_mean[3]) * beta[3] +\n          (zr^2 - X_mean[4]) * beta[4] + Y_mean\n  dcases <- yhat * fd_sd + fd_mean            # back to case-change units, per province\n  fut <- which(dates > hist_end)             # project future months only\n  proj <- last_obs + t(apply(dcases[, fut, drop = FALSE], 1, cumsum))\n  list(proj = proj, dates = dates[fut])\n}\n\n# scenario -> array (province x future-month x model), dropping unstable models\nproject_scenario <- function(scenario) {\n  tas <- cmip_tas[[scenario]]; pr <- cmip_pr[[scenario]]\n  nm  <- dim(tas$arr)[3]\n  lst <- lapply(seq_len(nm), function(m)\n    project_one(tas$arr[, , m], pr$arr[, , m], tas$dates)$proj)\n  arr  <- simplify2array(lst)                 # province x month x model\n  keep <- apply(arr, 3, function(x) all(is.finite(x)))\n  arr[, , keep, drop = FALSE]\n}\n\nfut_dates <- project_one(cmip_tas[[1]]$arr[, , 1], cmip_pr[[1]]$arr[, , 1],\n                         cmip_tas[[1]]$dates)$dates\nproj_arr  <- list(\"SSP1-2.6\" = project_scenario(\"SSP1-2.6\"),\n                  \"SSP5-8.5\" = project_scenario(\"SSP5-8.5\"))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Annual totals per province, with ensemble mean and interquartile band --------\nannual_proj <- function(arr, dates, scenario) {\n  yr <- lubridate::year(dates); years <- sort(unique(yr))\n  ap <- sapply(years, function(y)\n    apply(arr[, yr == y, , drop = FALSE], c(1, 3), sum))   # -> (province*?)...\n  ap <- array(ap, dim = c(length(provinces), dim(arr)[3], length(years)))  # prov x model x year\n  ap <- aperm(ap, c(1, 3, 2))                              # prov x year x model\n  data.frame(\n    province_en = rep(provinces, times = length(years)),\n    year = rep(years, each = length(provinces)),\n    scenario = scenario,\n    mean = as.vector(apply(ap, c(1, 2), mean)),\n    q25  = as.vector(apply(ap, c(1, 2), quantile, 0.25)),\n    q75  = as.vector(apply(ap, c(1, 2), quantile, 0.75))\n  )\n}\n\nproj_annual <- bind_rows(\n  annual_proj(proj_arr[[\"SSP1-2.6\"]], fut_dates, \"SSP1-2.6\"),\n  annual_proj(proj_arr[[\"SSP5-8.5\"]], fut_dates, \"SSP5-8.5\")\n)\n\nprint(ggplot(proj_annual, aes(year, mean, colour = scenario, fill = scenario)) +\n  geom_ribbon(aes(ymin = q25, ymax = q75), alpha = 0.2, colour = NA) +\n  geom_line(linewidth = 0.6) +\n  facet_wrap(~ province_en, scales = \"free_y\") +\n  scale_colour_manual(values = c(\"SSP1-2.6\" = \"#2166ac\", \"SSP5-8.5\" = \"#b2182b\")) +\n  scale_fill_manual(values   = c(\"SSP1-2.6\" = \"#2166ac\", \"SSP5-8.5\" = \"#b2182b\")) +\n  labs(x = \"year\", y = \"projected annual cases\",\n       title = \"Projected annual cases under CMIP6 (statistical/ARX model)\",\n       subtitle = \"Ensemble mean (line) and interquartile range (band). See caveat above.\") +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 20, hjust = 1)))\n```\n\n::: {.cell-output-display}\n![](session2_climate_data_files/figure-html/part6-plot-1.png){fig-align='center' width=1056}\n:::\n:::\n\n\n**6.1 The projection standardises the future climate using the *historical* mean and\nstandard deviation, not the future data's own. Why is that essential? What would go\nwrong if we standardised the future climate on itself?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n**6.2 Look at the projected trajectories and re-read the caveat. Which features of\nthese plots would you trust, and which would you not? How would you describe the\nresult honestly to a decision-maker?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n\n<p><input type=\"button\" value=\"Print this page\" onClick=\"window.print()\"></p>\n\n::: {.callout-tip collapse=\"true\"}\n## Solutions for Part 6: click to reveal (try the questions first)\n\n**6.1** The model was fitted on climate standardised by its *historical* mean and\nstandard deviation, so the coefficients only make sense on that same scale. If we\nre-standardised the future climate on itself, we would subtract off the very warming\n(or drying/wetting) trend we are trying to project; every period would look\n\"average\" relative to its own era, and the projected climate signal would vanish. We\nmust apply the historical scaling so that a genuinely hotter future shows up as a\nlarge positive standardised value.\n\n**6.2** Trust the *direction and relative* differences, e.g. that the higher-\nemissions scenario diverges from the lower one, and the ranking of provinces, more\nthan the absolute case numbers, which drift because of the cumulative-sum\nreconstruction. Honest framing to a decision-maker: \"this shows how a climate-driven\nstatistical model *responds* to two emissions futures; the shape and the gap between\nscenarios are informative, but the absolute counts decades out are illustrative, not\na forecast, and a mechanistic model would be needed for credible long-range numbers.\"\n:::\n\n---\n\n# Optional: a mechanistic SEIRS alternative\n\n::: speaker-note\nThis whole section is optional and more advanced: it lives behind an expandable\nbox so it does not interrupt the main flow, and so Session 3 can stay a clean group\ndiscussion. Run it only if the group powers through Parts 1–6 with time to spare, or\npoint interested participants to it afterwards. It reuses the case and climate data\nalready built above (no re-loading), fits a compartmental transmission model, and\ndoubles as a **worked code base for fitting a transmission model directly**. Keep the\noptimiser budget small for a live demo: the fit is deliberately not run to\nconvergence, and every number is illustrative.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Why an SEIRS model? (optional and more advanced; click to expand)\n\nThe model in Parts 5–6 is deliberately the simplest thing that works: one shared\nstatistical relationship between climate and the month-to-month *change* in cases. A\nmechanistic **SEIRS** model is the more biologically structured alternative. Instead\nof regressing cases on climate, it represents the disease process itself: people\nmove through Susceptible → Exposed → Infected → Recovered → Susceptible compartments\n, and lets **climate drive the transmission rate**. That buys three things the\nstatistical model cannot: per-province transmission with *shared* natural-history\nparameters (so provinces borrow strength); built-in saturation and waning immunity\n(so it cannot produce the negative or runaway counts a differenced model can); and a\ntemplate you can adapt to fit a transmission model directly to your own data. The\ncost is more assumptions and a harder fit.\n\nEach province runs an SEIRS model sharing the natural-history parameters but with a\nprovince- and time-varying transmission rate:\n\n$$\\frac{dS}{dt} = -\\beta(t) S I + \\omega R \\quad\n  \\frac{dE}{dt} = \\beta(t) S I - \\sigma E \\quad\n  \\frac{dI}{dt} = \\sigma E - \\gamma I \\quad\n  \\frac{dR}{dt} = \\gamma I - \\omega R$$\n\nwith $\\beta_p(t) = \\beta_{0,p}\\exp(b_{temp}\\, z_{temp}(p,t) + b_{rain}\\, z_{rain}(p,t))$,\nand reported cases modelled as\n$\\text{cases}_p(t) \\sim \\text{Poisson}(\\text{scale}_p \\cdot \\sigma E_p(t))$, fitted by\nmaximum likelihood.\n\n**Caveats: read before trusting any number.** The climate covariates stand in for\nmissing mosquito data; there are no population denominators (so `scale` absorbs\npopulation size and reporting rate); the natural-history parameters\n($\\sigma,\\gamma,\\omega$) are fitted freely rather than fixed to published\nvivax/falciparum biology; the two parasite species are pooled; and the optimiser uses\na small iteration budget so it runs quickly; it is **not** run to convergence. Treat\nevery output as illustrative of method, not as an estimate.\n\n**The data.** The SEIRS reuses the case matrix and per-province climate already built\nin Parts 2–3 and 5. The only difference is that it standardises climate **globally**\n(one shared scale) rather than per province, so that `b_temp`/`b_rain` are a single\ncomparable climate sensitivity.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# reuse cases_mat, clim_temp (Kelvin), clim_rain (m), popsd() from Part 5\nztemp <- (clim_temp - mean(clim_temp)) / popsd(clim_temp)\nzrain <- (clim_rain - mean(clim_rain)) / popsd(clim_rain)\ncat(sprintf(\"SEIRS inputs: %d provinces x %d months, %.0f total cases\\n\",\n            nrow(cases_mat), ncol(cases_mat), sum(cases_mat)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSEIRS inputs: 15 provinces x 15 months, 12829 total cases\n```\n\n\n:::\n:::\n\n\nThe model is built up in five small pieces below, then fitted. Read them in order.\n\n**Step 1: the transmission dynamics (the ODE right-hand side).** This is the SEIRS\nmodel itself: the instantaneous rate of change of each compartment. `state` is a\n5 × n matrix, one column per province, rows S, E, I, R, and C (a running count of\nnew infections), so everything is vectorised over provinces at once.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSUBSTEPS_PER_MONTH <- 20   # RK4 sub-steps per month\n\nseirs_rhs <- function(state, beta, sigma, gamma, omega) {\n  S <- state[1, ]; E <- state[2, ]; I <- state[3, ]; R <- state[4, ]\n  rbind(-beta * S * I + omega * R,     #  dS  (lose to infection, gain from waning immunity)\n         beta * S * I - sigma * E,     #  dE  (newly infected, then become infectious)\n         sigma * E   - gamma * I,      #  dI  (become infectious, then recover)\n         gamma * I   - omega * R,      #  dR  (recover, then lose immunity)\n         sigma * E)                    #  dC  (cumulative NEW infections)\n}\n```\n:::\n\n\n**Step 2: simulating it forward (fixed-step RK4).** We integrate the ODE month by\nmonth using a fixed-step Runge–Kutta (RK4) scheme with `SUBSTEPS_PER_MONTH` steps per\nmonth, for all provinces simultaneously. A burn-in lets the model settle before we\nrecord anything, and we reset the accumulator `C` at the start of each month so that\n`incidence` holds the new infections *within* that month.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimulate_incidence <- function(beta, sigma, gamma, omega,\n                               i0 = 1e-4, e0 = 1e-4, burn_in_months = 12) {\n  n_prov <- nrow(beta); n_months <- ncol(beta); dt <- 1 / SUBSTEPS_PER_MONTH\n  state <- rbind(rep(1 - i0 - e0, n_prov), rep(e0, n_prov),\n                 rep(i0, n_prov), rep(0, n_prov), rep(0, n_prov))\n  step <- function(state, beta_m) {                    # one RK4 sub-step\n    k1 <- seirs_rhs(state,              beta_m, sigma, gamma, omega)\n    k2 <- seirs_rhs(state + 0.5*dt*k1,  beta_m, sigma, gamma, omega)\n    k3 <- seirs_rhs(state + 0.5*dt*k2,  beta_m, sigma, gamma, omega)\n    k4 <- seirs_rhs(state + dt*k3,      beta_m, sigma, gamma, omega)\n    state + (dt/6) * (k1 + 2*k2 + 2*k3 + k4)\n  }\n  if (burn_in_months > 0) {                            # settle using month-1 transmission\n    beta0_m <- beta[, 1]\n    for (b in seq_len(burn_in_months)) {\n      for (s in seq_len(SUBSTEPS_PER_MONTH)) state <- step(state, beta0_m)\n      state[5, ] <- 0\n    }\n  }\n  incidence <- matrix(0, n_prov, n_months)\n  for (m in seq_len(n_months)) {\n    state[5, ] <- 0; beta_m <- beta[, m]               # reset accumulator; use this month's beta\n    for (s in seq_len(SUBSTEPS_PER_MONTH)) state <- step(state, beta_m)\n    incidence[, m] <- state[5, ]\n    state[1:4, ] <- pmin(pmax(state[1:4, ], 0), 1)     # keep compartments in [0, 1]\n  }\n  incidence\n}\n```\n:::\n\n\n**Step 3: unpacking the parameters.** The optimiser works in an unconstrained,\nlog-transformed space so that rates stay positive. This turns the flat parameter\nvector back into named, natural-scale quantities: the shared natural-history rates,\nthe two climate sensitivities, and the per-province baseline transmission `beta0` and\nreporting `scale`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nunpack_params <- function(params, n) {\n  list(sigma = exp(params[1]), gamma = exp(params[2]), omega = exp(params[3]),\n       b_temp = params[4], b_rain = params[5],\n       beta0 = exp(params[6:(5 + n)]), scale = exp(params[(6 + n):(5 + 2*n)]))\n}\n```\n:::\n\n\n**Step 4: the likelihood.** Given a parameter vector, build the climate-forced\ntransmission rate `beta_t`, simulate the incidence, and score it against the observed\ncounts with a Poisson negative log-likelihood, the quantity the optimiser minimises.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nneg_log_lik <- function(params, cases, ztemp, zrain) {\n  n <- nrow(cases); p <- unpack_params(params, n)\n  beta_t <- p$beta0 * exp(p$b_temp * ztemp + p$b_rain * zrain)   # climate forces transmission\n  beta_t <- pmin(pmax(beta_t, 1e-6), 50)\n  incidence <- simulate_incidence(beta_t, p$sigma, p$gamma, p$omega)\n  lam <- pmax(p$scale * incidence, 1e-8)                         # expected reported cases\n  sum(lam - cases * log(lam))   # Poisson NLL (constant omitted)\n}\n```\n:::\n\n\n**Step 5: sensible starting values.** A reasonable initial guess for the optimiser:\nincubation ~0.5 months, infectious ~1 month, immunity ~6 months, no climate effect to\nbegin with, and per-province baselines scaled to each province's mean caseload.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndefault_x0 <- function(cases) {\n  n <- nrow(cases)\n  c(log(1/0.5), log(1/1.0), log(1/6.0), 0, 0,      # sigma, gamma, omega, b_temp, b_rain\n    log(rep(2.5, n)),                              # beta0 (per province)\n    log(pmax(rowMeans(cases), 1) * 50))            # scale (per province)\n}\n```\n:::\n\n\n**Step 6: fit.** Now minimise the negative log-likelihood with a bounded optimiser\n(`L-BFGS-B`). The `lower`/`upper` vectors keep every parameter in a biologically\nplausible range (incubation/infectious periods between ~0.05 and 3 months, immunity\nbetween 0.5 and 36 months, the climate sensitivities within ±2), and `maxit` is kept\ndeliberately small so it finishes quickly (raise it for a real fit).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn <- nrow(cases_mat)\nx0 <- default_x0(cases_mat)\nlower <- c(log(1/3.0), log(1/3.0), log(1/36.0), -2, -2,\n           rep(log(0.05), n), rep(log(1.0),  n))\nupper <- c(log(1/0.05), log(1/0.05), log(1/0.5), 2, 2,\n           rep(log(30),   n), rep(log(1e9),  n))\n\n# maxit kept small so this runs quickly; raise it for a production fit. ndeps sets\n# the finite-difference gradient step to match SciPy's default, so this tracks the\n# notebook's fit as closely as the two L-BFGS-B implementations allow (see the note\n# in python_workflow/compare.R about why the fitted parameters are close, not exact).\nfit <- optim(x0, neg_log_lik, method = \"L-BFGS-B\",\n             lower = lower, upper = upper,\n             cases = cases_mat, ztemp = ztemp, zrain = zrain,\n             control = list(maxit = 20, ndeps = rep(1e-8, length(x0)))) \np <- unpack_params(fit$par, n)\n\ncat(sprintf(\"convergence code=%d  nll=%.1f\\n\", fit$convergence, fit$value))\ncat(sprintf(\"incubation period 1/sigma = %.2f months\\n\", 1/p$sigma))\ncat(sprintf(\"infectious period 1/gamma = %.2f months\\n\", 1/p$gamma))\ncat(sprintf(\"immunity duration 1/omega = %.2f months\\n\", 1/p$omega))\ncat(sprintf(\"climate sensitivity b_temp = %+.3f  b_rain = %+.3f\\n\", p$b_temp, p$b_rain))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nconvergence code=1  nll=-52416.8\nincubation period 1/sigma = 0.18 months\ninfectious period 1/gamma = 0.86 months\nimmunity duration 1/omega = 9.49 months\nclimate sensitivity b_temp = +0.059  b_rain = +0.268\n```\n\n\n:::\n:::\n\n\n**Step 7: diagnostics.** Finally, rebuild the fitted incidence from the estimated\nparameters and compare it, province by province, against the observed monthly counts.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbeta_fit <- p$beta0 * exp(p$b_temp * ztemp + p$b_rain * zrain)\nlam_fit  <- p$scale * simulate_incidence(beta_fit, p$sigma, p$gamma, p$omega)\n\nss_res <- sum((cases_mat - lam_fit)^2)\nss_tot <- sum((cases_mat - mean(cases_mat))^2)\ncat(sprintf(\"pseudo-R2 (vs fitted lambda): %.3f\\n\", 1 - ss_res / ss_tot))\n\ndiag_long <- bind_rows(\n  as.data.frame(cases_mat) %>% tibble::rownames_to_column(\"province_en\") %>%\n    pivot_longer(-province_en, names_to = \"month\", values_to = \"cases\") %>% mutate(series = \"observed\"),\n  as.data.frame(lam_fit) %>% `rownames<-`(rownames(cases_mat)) %>%\n    `colnames<-`(colnames(cases_mat)) %>%\n    tibble::rownames_to_column(\"province_en\") %>%\n    pivot_longer(-province_en, names_to = \"month\", values_to = \"cases\") %>% mutate(series = \"fitted\")\n) %>% mutate(month = as.Date(month))\n\nprint(ggplot(diag_long, aes(month, cases, colour = series)) +\n  geom_line(linewidth = 0.6) +\n  facet_wrap(~ province_en, scales = \"free_y\") +\n  scale_colour_manual(values = c(observed = \"black\", fitted = \"red\")) +\n  labs(x = \"date\", y = \"monthly cases\",\n       title = \"Observed vs SEIRS-fitted monthly cases\") +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 20, hjust = 1)))\n```\n\n::: {.cell-output-display}\n![](session2_climate_data_files/figure-html/seirs-diag-1.png){fig-align='center' width=1056}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\npseudo-R2 (vs fitted lambda): 0.944\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n**A note on identifiability.** Fitting this exact model in both R and Python is\ninstructive. The two reach the *same* likelihood and predict essentially the same\ncases (per-province annual totals agree to about 0.3%), yet their fitted `beta0`\nand `scale` differ by a couple of percent. That is a textbook symptom of\n**non-identifiability**: `beta0` (baseline transmission) and `scale` (population ×\nreporting rate) trade off to set the case *level*, so the optimiser can shuffle\nmagnitude between them, and the natural-history rates ($\\sigma,\\gamma,\\omega$) are\nonly weakly constrained by the data. It is concrete evidence for the warning above:\ntrust the model's *predictions* and the climate sensitivities `b_temp`/`b_rain`, not\nthe individual parameter values. (This is why the verification in\n`python_workflow/compare.R` checks the fitted incidence and climate coefficients, and\ntreats the level parameters as illustrative.)\n\n**Discussion (SEIRS): the statistical model (Parts 5–6) and this mechanistic model\nboth link climate to malaria. What can the mechanistic model tell you that the\nstatistical one cannot, and vice versa? And why are the fitted natural-history\nparameters ($\\sigma,\\gamma,\\omega$) a weakness here, and how would you fix it?**\n\n```{=html}\n<textarea cols=\"127\" rows=\"4\"></textarea>\n```\n<p><br></p>\n:::\n\n<p><input type=\"button\" value=\"Print this page\" onClick=\"window.print()\"></p>\n",
    "supporting": [
      "session2_climate_data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}